### ISSUE TITLE
Avoid installing KFP on components using PYTHON_IMAGE

### ISSUE THREAD

**Issue by leseb** [opendatahub-io/ilab-on-ocp#175]
We should avoid installing any packages at runtime and thus use an image that has the KFP package installed.

This could mean a few things:

* stop using the PYTHON_IMAGE and use RHELAI_IMAGE: simplest method but expensive since those components are small python functions
* try to avoid those components: requires further investigation

**Comment by tumido** [comment]
FTR, we've started escalating this to the stake holders.
