### ISSUE TITLE
Need to make the GPU architecture configurable

### ISSUE THREAD

**Issue by cooktheryan** [opendatahub-io/ilab-on-ocp#179]
For Phase 3 we need to not default to NVIDIA GPU but allow the user to set the value for the accelerator

**Comment by cooktheryan** [comment]
This also means we would need to swap images between architectures because RHEL AI with AMD is not the same RHEL AI image we have been using

**Comment by tumido** [comment]
Swapping images can be a problem... image name is not templatable from parameters.

**Comment by tumido** [comment]
It was decided that for the time being we support NVIDIA only. Closing this issue, since it's specific to Phase 3. Feel free to reopen once it becomes relevant again.
