### ISSUE TITLE
Bump KFP version to 2.10.1 to address accelerator bug in kfp 2.10.0

### ISSUE THREAD

**Issue by MichaelClifford** [opendatahub-io/ilab-on-ocp#186]
See Issue: https://github.com/kubeflow/pipelines/issues/11374 and PR https://github.com/kubeflow/pipelines/pull/11373 for additional details.

**Comment by cooktheryan** [comment]
We will need to update the request to RHEL AI image to support this

**Comment by MichaelClifford** [comment]
@cooktheryan I added a question to RHEL AI folks to see if we can get this into the next image.
