### ISSUE TITLE
Re-evaluate default param values for KFP

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/ilab-on-ocp#211]
Let's make sure default parameters for KFP do match requirements and make sense in generic environment.

**Comment by MichaelClifford** [comment]
I think we probably want to stick closely with the default params they have here: 

https://github.com/instructlab/instructlab/blob/main/tests/testdata/default_config.yaml

**Comment by leseb** [comment]
> I think we probably want to stick closely with the default params they have here:
> 
> https://github.com/instructlab/instructlab/blob/main/tests/testdata/default_config.yaml

Note that this is not 100% perfect since the option are adapted based on the "profile" (hw detection/platform) used. However, this is certainly a solid foundation.
