### ISSUE TITLE
RHEL AI Image CMD issue

### ISSUE THREAD

**Issue by cooktheryan** [opendatahub-io/ilab-on-ocp#64]
Currently, the RHEL AI image does not work with KFP. We need to make modifications to the image

**Comment by leseb** [comment]
Fixed by https://github.com/redhat-et/ilab-on-ocp/pull/129?

**Comment by leseb** [comment]
I believe we now have a new image with KFP, can we close this?

**Comment by leseb** [comment]
Closing this for now. @cooktheryan, feel free to let me know if there’s any concern!
